#include "websocket_internal.h"
#include "esp_log.h"
#include "esp_websocket_client.h"
#include <stdio.h>
#include <string.h>

static const char *TAG = "WS_TOOL";

bool websocket_send_tool_response(const char *id, const char *name, bool success)
{
    if (!id || !name || !client || !is_connected || websocket_tx_error) return false;
    if (!esp_websocket_client_is_connected(client)) return false;

    // Gemini Live WebSocket requires toolResponse.functionResponses[].
    // The function name and id are generated by Gemini; accept only the
    // expected local function name and a conservative id character set.
    if (strcmp(name, "control_device") != 0) return false;
    for (const char *p = id; *p; ++p) {
        if (!( (*p >= 'a' && *p <= 'z') || (*p >= 'A' && *p <= 'Z') ||
               (*p >= '0' && *p <= '9') || *p == '_' || *p == '-' )) {
            ESP_LOGW(TAG, "Tool call id ditolak karena karakter tidak aman");
            return false;
        }
    }

    char payload[512];
    int len = snprintf(
        payload, sizeof(payload),
        "{\"toolResponse\":{\"functionResponses\":[{\"id\":\"%s\",\"name\":\"%s\",\"response\":{\"result\":\"%s\"}}]}}",
        id, name, success ? "ok" : "error");
    if (len <= 0 || (size_t)len >= sizeof(payload)) return false;

    int sent = esp_websocket_client_send_text(client, payload, len, pdMS_TO_TICKS(5000));
    if (sent != len) {
        ESP_LOGW(TAG, "Tool response gagal dikirim: sent=%d expected=%d", sent, len);
        return false;
    }

    ESP_LOGI(TAG, "Tool response terkirim: %s id=%s result=%s",
             name, id, success ? "ok" : "error");
    return true;
}
